Support for WT32-ETH01 board
hideakitai/ArtNet pull request #37
Opened 2022-05-09 09:54 UTC by burner-

These changes provide support for ESP32 framework own ETH library. Library support by default at least WT32-ETH01 board. At ESP32.

2022-10-01 10:44 UTC, Jack079 commented
Hi, 
Do you have a working example script?

I did add line 584 - 589 to ArtnetCommon.h
And add the ArtnetETH.h file.

I tried the ethernet reciever example and changed to ArtnetETH.h,  now I get a 'Ethernet was not delared in this scope' error.

In the Wifi receiver example  it was unable to connect to my network.

2022-10-01 10:53 UTC, burner- commented
> Hi, Do you have a working example script?
> 
> I did add line 584 - 589 to ArtnetCommon.h And add the ArtnetETH.h file.
> 
> I tried the ethernet reciever example and changed to ArtnetETH.h, now I get a 'Ethernet was not delared in this scope' error.
> 
> In the Wifi receiver example it was unable to connect to my network.

I cannot put full code at this point. But there is headers. 
`#define ETH_PHY_ADDR        1
#define ETH_PHY_TYPE    ETH_PHY_LAN8720
#define ETH_PHY_POWER  16
#define ETH_PHY_MDC     23
#define ETH_PHY_MDIO    18
#define ETH_CLK_MODE    ETH_CLOCK_GPIO0_IN  //  ETH_CLOCK_GPIO17_OUT
#include <ETH.h>

#include <WiFi.h>
#include <WiFiClient.h>
#include <WiFiUdp.h>


#include <time.h>
#include "FS.h"
#include "SPIFFS.h"
#include "update.h"

#include <ArtnetETH.h> // https://github.com/burner-/ArtNet`

2022-11-15 10:01 UTC, PureTek-Innovations commented
Hi @burner- 
Thank you very much for your work on this library and for this pull request.
I'm using your fork of the library to send Artnet data from a WT32-ETH01 board.
I had to make some minor changes to get it to work.

I changed lines 57,58 and 59 in ArtnetETH.h
from
using ArtnetWiFi = arx::artnet::Manager<WiFiUDP>;
using ArtnetWiFiSender = arx::artnet::Sender<WiFiUDP>;
using ArtnetWiFiReceiver = arx::artnet::Receiver<WiFiUDP>;

to
using Artnet = arx::artnet::Manager<WiFiUDP>;
using ArtnetSender = arx::artnet::Sender<WiFiUDP>;
using ArtnetReceiver = arx::artnet::Receiver<WiFiUDP>;

It now works brilliantly and is almost three times faster, on my setup, than streaming the data just over WiFi. I stream the data to the router by Ethernet and then from the router to the nodes by WiFi.
I'm currently driving 11,175 LEDs, split across 4 ESP32 nodes, at 57 frames per second and losing less than 0.1% of frames.

Again, thank you very much to everyone who has worked on this library.

Just to help other people, including @Jack079, my minimal setup code is:

#include <ArtnetETH.h>
#include <ETH.h>
#define ETH_CLK_MODE    ETH_CLOCK_GPIO0_IN
#define ETH_POWER_PIN  16
#define ETH_TYPE        ETH_PHY_LAN8720
#define ETH_ADDR        1
#define ETH_MDC_PIN     23
#define ETH_MDIO_PIN    18

Artnet artnet;

setup(){
ETH.begin(ETH_ADDR, ETH_POWER_PIN, ETH_MDC_PIN, ETH_MDIO_PIN, ETH_TYPE, ETH_CLK_MODE);
artnet.begin();
}

2022-11-15 10:17 UTC, burner- commented
@PureTek-Innovations 2793led per driver? What led you use or do you use multiple channels?

2022-11-15 10:29 UTC, PureTek-Innovations commented
@burner- 
I'm using WS2815s split over 9 pins, the maximum strip length is about 325 leds.
I'm using this library to receive the data and write it to the leds.
https://github.com/hpwit/artnetESP32

I have only fitted half the leds so far, there will be about 22,000 when it's done. 
There's an update on the project on r/FastLED here:
https://www.reddit.com/r/FastLED/comments/yrorqg/spin_room_update_over_11000_ws2815s_up_and

2022-11-15 10:34 UTC, burner- commented
@PureTek-Innovations nice do you have possibility to publish code? I would see that how you drive those 9 pins with same device.

2022-11-15 10:40 UTC, PureTek-Innovations commented
@burner- Here's the receiving code
https://gist.github.com/PureTek-Innovations/88810a96100c3ae8ce119965c521663e

2023-08-06 23:31 UTC, hideakitai requested changes
Thanks for your contribution. Additionally, please add a description of the ETH library in README.

2023-08-06 23:31 UTC, hideakitai commented on ArtnetETH.h
This header includes a lot of unnecessary codes. This is minimal and enough.

```cpp
#pragma once
#ifndef ARTNET_ETH_H
#define ARTNET_ETH_H

#define ARTNET_ENABLE_ETH

#include <Arduino.h>
#include "Artnet/util/ArxTypeTraits/ArxTypeTraits.h"
#include "Artnet/util/ArxContainer/ArxContainer.h"
#include <ETH.h>
#include <WiFiUdp.h>
#include "Artnet/ArtnetCommon.h"

// ETH.h is a library for Ethernet PHY, but we should use the WiFi library's APIs for server/client
using ArtnetWiFi = arx::artnet::Manager<WiFiUDP>;
using ArtnetWiFiSender = arx::artnet::Sender<WiFiUDP>;
using ArtnetWiFiReceiver = arx::artnet::Receiver<WiFiUDP>;

#endif // ARTNET_ETH_H
```

2023-08-06 23:31 UTC, hideakitai commented on ArtnetETH.h
> +#endif
These definitions should not be included in the library. Please remove these definitions and create examples by using them. I want `Artnet/examples/ETH/receive_fastled`, `receiver`, `send_receive`, and `sender`.

2023-08-13 15:18 UTC, hideakitai commented
Thank you for your contribution. Fixed by https://github.com/hideakitai/ArtNet/pull/48

2023-08-13 15:18 UTC, closed without merging