Create ArtnetEtherENC.h
hideakitai/ArtNet pull request #79
Opened 2024-01-05 15:20 UTC by MrFrangipane

Hello

Thank you for this awesome library.

Is it possible to make possible the use of the following library ?

Allows to use https://github.com/JAndrassy/EthernetENC

For now, I modifiy files manually, it would be awesome to have this embedded in the lib, if It helps someone else

All the best,
Val

2024-01-05 21:51 UTC, hideakitai requested changes
Thank you for your contribution! Could you add examples and workflows for them?

2024-01-07 15:51 UTC, MrFrangipane commented
Hi !

Thanks for your response !

I'll look into it :)

Val

2024-01-08 11:01 UTC, MrFrangipane commented
Hi,

I tried to add what you requested :)

The wiring diagram was taken from https://github.com/Juddling/pi-pico-enc28j60 and is reported to be made by https://github.com/tobiasvogel

I'm not familiar with workflows I copied/pasted previous sections

Hope this helps,
All the best !

2024-01-08 11:15 UTC, MrFrangipane commented
Also,

It's probably not the place to ask you about this (sorry), I see here than only four callbacks are allowed https://github.com/hideakitai/ArtNet#subscribing-callbacks-with-net-sub-net-and-universe-as-you-like, why is it so ?

Thank you again,
Val

2024-01-08 14:07 UTC, hideakitai commented
About callbacks, the limitation has been removed, but README is not fixed…

https://github.com/hideakitai/ArtNet/issues/59

2024-01-08 14:20 UTC, hideakitai reviewed
Commented

2024-01-08 14:20 UTC, hideakitai commented on .github/workflows/build.yml
> +              vendor: rp2040
I think EtherENC is available for any platform. If so, please add “board” and “include” as same as the “build-ethernet”.

2024-01-08 14:20 UTC, hideakitai commented on README.md
> +- Raspberry Pi Pico with ENC28J60 (please read following section)
All platforms that can use EtherENC can be supported, I think.

2024-01-08 14:51 UTC, MrFrangipane commented on README.md
> +- Raspberry Pi Pico with ENC28J60 (please read following section)
You're right,

I'll check the library documentation

2024-01-08 14:51 UTC, MrFrangipane commented on .github/workflows/build.yml
> +              vendor: rp2040
Noted, will do

2024-01-08 21:07 UTC, hideakitai commented
> Oh OK i was surprised to see it working, do you want me to remove this section from the readme as well ?

It’s great if you can! Thank you!

2024-01-08 22:23 UTC, MrFrangipane commented
I see some builds have failed

Should we remove those boards from the build and list supported boards in the docs ?

- UNO has `not enough memory`

- I see errors regarding MAC Address (which I had to remove)

```
   /home/runner/Arduino/libraries/ArtNet/Artnet/ArtPollReply.h:68:15: warning: 'my_mac' is used uninitialized in this function [-Wuninitialized]
           memcpy(r.mac, my_mac, 6);
           ~~~~~~^~~~~~~~~~~~~~~~~~
```

2024-01-08 22:27 UTC, MrFrangipane commented
> > Oh OK i was surprised to see it working, do you want me to remove this section from the readme as well ?
> 
> It’s great if you can! Thank you!

It's done, I copied the explanation you gave in #59

2024-01-09 00:11 UTC, hideakitai commented
> Although I'm not sure what is meant by "making public 4 of them"

`PollReply` has the information of four input/output ports. So current implementation is, you can subscribe many universes but four of them are informed by `PollReply`. (But this implementation is not preferred, so I should fix it https://art-net.org.uk/how-it-works/discovery-packets/artpollreply/)

2024-01-09 00:17 UTC, hideakitai reviewed
Added suggestion for README

2024-01-09 00:17 UTC, hideakitai commented on README.md
> +PortTypes, GoodInput/Output, SwIn, etc., are limited to 4 ports. If more than 4 callbacks are needed, it is better to subscribe to more than four and make public 4 of them
```suggestion
PortTypes, GoodInput/Output, SwIn, etc., are limited to 4 ports. Only the first four ports are reflected if you subscribe to more than four callbacks.
```

2024-01-09 01:04 UTC, hideakitai commented on .github/workflows/build.yml
> +            - examples/EthernetENC
Following `sketch-paths` is better to avoid memory shortage for avr

```suggestion
          sketch-paths: |
            - examples/Ethernet/receiver
            - examples/Ethernet/sender
```

2024-01-09 01:10 UTC, hideakitai commented on .github/workflows/build.yml
> +            name: uno
Could you comment out these lines and add a comment like "temporarily disabled because of memory shortage of `sender` example"

2024-01-09 01:28 UTC, hideakitai commented on Artnet/Receiver.h
>  #endif
The latest (on GitHub) version has the `MACAddress()` method.

https://github.com/JAndrassy/EthernetENC/blob/3a50d3aa9c1510e4090d1763ec3e91c700b764a1/src/Ethernet.h#L99

So, could you modify these lines as follows? (`ESP8266` also has `MACAddress()` method now, `#if` directive has removed)

```suggestion
        Ethernet.MACAddress(mac);
```

2024-01-09 01:30 UTC, hideakitai commented
@MrFrangipane Maybe the suggestions above can fix workflows. Could you try to implement them?

2024-01-09 10:37 UTC, MrFrangipane commented
> > Although I'm not sure what is meant by "making public 4 of them"
> 
> `PollReply` has the information of four input/output ports. So current implementation is, you can subscribe many universes but four of them are informed by `PollReply`. (But this implementation is not preferred, so I should fix it https://art-net.org.uk/how-it-works/discovery-packets/artpollreply/)

Thank you ! I get it now :)

2024-01-09 11:11 UTC, MrFrangipane commented on Artnet/Receiver.h
>  #endif
Hi,

I was able to compile my sketch after cloning the latest ENC  library and removing the `#if` directive

Readme and workflow have been updated to use git instead of regular installation

2024-01-09 11:23 UTC, MrFrangipane commented
> @MrFrangipane Maybe the suggestions above can fix workflows. Could you try to implement them?

Sure, changes have been made :)

_I realized too late i could directly commit your suggestions, I'll know for next time_

2024-01-09 14:15 UTC, hideakitai commented
Ah, maybe this is a bug of EthernetENC…

2024-01-09 23:20 UTC, hideakitai commented
Please comment out esp32, s3, and c3 from workflow. But it is NOT unavailable for esp32 series, I will send pull request to EtherENC :)

2024-01-09 23:25 UTC, hideakitai commented
> state to not use ESP32 with EthernetENC in the readme ?

Could you add a same note as README of EtherENC?

> For ESP32 it is better than using a MAC layer module like the enc28j60 to use a PHY layer LAN module like LAN8720 supported by the ESP32 MAC peripheral and the Arduino boards support package.

2024-01-10 04:24 UTC, hideakitai commented
Created a PR on EthernetENC https://github.com/JAndrassy/EthernetENC/pull/58

2024-01-10 04:25 UTC, hideakitai commented on .github/workflows/build.yml
> +            - source-url: https://github.com/JAndrassy/EthernetENC.git
You can pass workflow temporary replaced by my fork

```suggestion
            - source-url: https://github.com/hideakitai/EthernetENC.git
              version: fix/compile-error-on-esp32-github-actions

```

2024-01-10 06:18 UTC, hideakitai commented on .github/workflows/build.yml
> +            - source-url: https://github.com/JAndrassy/EthernetENC.git
Aboe PR was rapidly merged, so there is no need to replace :)

https://github.com/JAndrassy/EthernetENC/pull/58

2024-01-10 07:09 UTC, MrFrangipane commented on .github/workflows/build.yml
> +            - source-url: https://github.com/JAndrassy/EthernetENC.git
perfect !

2024-01-10 07:26 UTC, hideakitai commented
If you finish working on this PR, please mention me!

2024-01-10 08:15 UTC, MrFrangipane commented
Hi

Thank you for your help again !

I realized only 2 examples were compiled, so I added them to the workflow

```yaml
sketch-paths: |
  - examples/EthernetENC/receive_fastled
  - examples/EthernetENC/receiver
  - examples/EthernetENC/send_receive
  - examples/EthernetENC/sender
```

This revealed that FastLED is not supporting `mkrvidor4000` boards. What do you prefer ?

- remove the board from tests and leave fastled enabled for the others
- remove the FastLED tests for all boards and leave `mkrvidor4000` board enabled

It seems to be the last thing we have to address before merging 🥳

2024-01-10 08:24 UTC, hideakitai commented
Yeah, mkrvidor is not supported. Hmm.. I prefer 

> remove the board from tests and leave fastled enabled for the others

2024-01-10 08:34 UTC, MrFrangipane commented
> Thank you! Yeah, mkrvidor is not supported. Hmm.. I prefer
> 
> > remove the board from tests and leave fastled enabled for the others

@hideakitai board has been disabled and FastLED reinstated

All tests seems to have passed :)

2024-01-10 08:41 UTC, hideakitai commented
All checks passed, thank you! I'll review the code again :)

2024-01-10 08:44 UTC, hideakitai approved these changes
There is one typo, but LGTM

2024-01-10 08:44 UTC, hideakitai commented on README.md
> +- Anyplatform supported by ENC28J60 (please read following section)
typo
```suggestion
- Any platform supported by ENC28J60 (please read following section)
```

2024-01-10 08:53 UTC, MrFrangipane commented
> There is one typo, but LGTM

Suggested fix was commited :)

2024-01-10 09:01 UTC, merged

2024-01-10 09:02 UTC, hideakitai commented
Thank you for your contribution!

2024-01-10 09:03 UTC, hideakitai commented
Please close https://github.com/hideakitai/ArtNet/issues/80 :) Thanks again!

2024-01-10 09:10 UTC, MrFrangipane commented
Awesome !

Thank you for all those wonderful libraries 🙏